# docker-compose.yml
# docker-compose up
version: '3'
services:  
  rvizweb:
    image: "rvizweb:noetic"
    container_name: rvizweb
    # for windows and mac, use 'network_mode: bridge'
    network_mode: host  
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
